oc_users_management:
    path:   /manage/users
    defaults: 
        _controller: OCUserBundle:UserManagement:getUsers

oc_user_management:
    path:   /manage/user
    defaults:
        _controller: OCUserBundle:UserManagement:getUser

oc_user_management_noRoleMessage:
    path: /norole
    defaults:
        _controller: OCUserBundle:UserManagement:noRoleManage