oc_users_management:
    path:   /manageUsers
    defaults: 
        _controller: OCUserBundle:UserManagement:getUsers

oc_user_management:
    path:   /
    defaults:
        _controller: OCUserBundle:UserManagement:getUser