<?php

namespace OC\StockManagementBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFirstLevelCategories() {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.parentId is NULL')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function getChildCategories($parentCategoryId) {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.parentId = :parentId')
                ->setParameter('parentId', $parentCategoryId)
        ;

        return $qb
        ->getQuery()
        ->getResult()
    ;
    }
}
