<?php

namespace OC\StockManagementBundle\Repository;

/**
 * CategoryTreesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTreesRepository extends \Doctrine\ORM\EntityRepository
{
}
