<?php

namespace OC\StockManagementBundle\Repository;

/**
 * MarketplaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketplaceRepository extends \Doctrine\ORM\EntityRepository
{
}
