


oc_stock_management_viewCategory:
    path:     /get/categories
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getCategories

oc_stock_management_getProducts:
    path:   /get/products
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getProducts

oc_stock_management_manageCategories:
    path:     /manage/categories
    defaults:
        _controller: OCStockManagementBundle:StockManagement:manageCategories

oc_stock_management_deleteLowSwtock:
    path:   /reset_low_stock
    defaults:
        _controller: OCStockManagementBundle:StockManagement:resetLowStock

oc_stock_management_home:
    path:   /
    defaults:
        _controller: OCStockManagementBundle:StockManagement:homeRedirect



