


oc_stock_management_viewCategory:
    path:     /getCategories
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getCategories

oc_stock_management_getProducts:
    path:   /getProducts
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getProducts

oc_stock_management_manageCategories:
    path:     /manageCategory
    defaults:
        _controller: OCStockManagementBundle:StockManagement:manageCategories

oc_stock_management_deleteLowSwtock:
    path:   /resetLowStock
    defaults:
        _controller: OCStockManagementBundle:StockManagement:resetLowStock



