


oc_stock_management_viewCategory:
    path:     /get/categories
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getCategories

oc_stock_management_getProducts:
    path:   /get/products
    defaults:
        _controller: OCStockManagementBundle:StockManagement:getProducts

oc_stock_management_manageCategories:
    path:     /
    defaults:
        _controller: OCStockManagementBundle:StockManagement:manageCategories

oc_stock_management_deleteLowSwtock:
    # Conservé au cas où, à supprimer
    # path:   /resetLowStock
    path:   /reset_low_stock
    defaults:
        _controller: OCStockManagementBundle:StockManagement:resetLowStock



