services:
    oc_platform.get.catalog:
        class: OC\StockManagementBundle\CatalogGetter\OCCatalogGetter

    oc_platform.get.products:
        class: OC\StockManagementBundle\ProductsGetter\OCProductsGetter

    oc_platform.get.lowStockProductsCSV:
        class: OC\StockManagementBundle\LowStockProductsCSVGetter\OCLowStockProductsCSVGetter

    oc_platform.compare.productsVsCategoriesStock:
        class: OC\StockManagementBundle\ProductsVsCategoriesStockComparator\OCProductsVsCategoriesStockComparator

    oc_platform.update.categories:
        class: OC\StockManagementBundle\CategoriesUpdater\OCCategoriesUpdater
